name: Linux (QT,CLI)

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - name: install deps
      run: |
            sudo add-apt-repository -y ppa:bitcoin/bitcoin
            sudo apt-get update
            sudo apt-get install libdb4.8-dev libdb4.8++-dev -y
            sudo apt-get install build-essential libtool autotools-dev autoconf pkg-config -y
            sudo apt-get install libssl1.0-dev -y
            sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler -y
            sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 libqt5svg5-dev libqt5charts5-dev qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libqrencode-dev -y
            sudo apt-get install libboost-all-dev -y
            
            
    - uses: actions/checkout@v1   
    - name: autogen.sh
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make -j 2          
    - name: make install
      run: make install DESTDIR=/home/runner/work/Bitradio/Bitradio/installer -j 2  
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Wallet
        path: /home/runner/work/Bitradio/Bitradio/installer
